---

- name: "Look up Sonar URL"
  command: >
    oc get route {{ sonarqube_name | default('sonarqube') }} -n {{ sonarqube_namespace }} -o custom-columns=ROUTE:.spec.host --no-headers
  register: sonarqube_url_result
  when:
  - sonarqube_url is not defined or sonarqube_url|trim == ''

- name: "Set sonarqube_url Result"
  set_fact:
    sonarqube_url: "{{ sonarqube_url_result.stdout }}"
  when:
  - sonarqube_url is not defined or sonarqube_url|trim == ''

- name: "Ensure Sonar is available before attempting to communicate"
  include_tasks: wait-for-sonar.yml
