---

- name: "Ensure the Sonar Server is Up"
  uri:
    url: "https://{{ sonarqube_url }}/api/system/ping"
    method: GET
    status_code: 200
    user: "{{ sonarqube_user }}"
    password: "{{ sonarqube_password }}"
    force_basic_auth: yes
    validate_certs: "{{ sonarqube_validate_certs }}"
  register: sonarqube_server_check_result
  until: sonarqube_server_check_result is success
  retries: '{{ sonarqube_server_poll_retries }}'
  delay: '{{ sonarqube_server_poll_delay_in_seconds }}'

